5 > 4
"ананас" > "яблоко"
"2" > "12"
undefined == null
undefined === null
null == "\n0\n"
null === +"\n0\n"
alert(5 > 4)
alert("ананас" > "яблоко")
alert("2" > "12")
alert(undefined == null)
alert(undefined === null)
alert(null == "\n0\n")
alert(null === +"\n0\n")